CREATE TYPE "FormaMesa" AS ENUM ('RECTANGULAR', 'CIRCULAR');

ALTER TABLE "Mesa" ADD COLUMN "forma" "FormaMesa" NOT NULL DEFAULT 'RECTANGULAR';
ALTER TABLE "Mesa" ADD COLUMN "ancho" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Mesa" ADD COLUMN "alto" DOUBLE PRECISION NOT NULL DEFAULT 1;
